-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (1 - COALESCE(D.DISCOUNT_RATE, 0) / 100.0)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID 
    AND (H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01') 
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE 
    AND D.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('SUV', '세단') 
GROUP BY 
    C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, D.DISCOUNT_RATE
HAVING 
    FEE >= 500000 AND FEE < 2000000
    AND COUNT(H.HISTORY_ID) = 0
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE ASC, 
    C.CAR_ID DESC;