-- 코드를 작성해주세요
SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, Y.YEAR_MAX - D.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA D
INNER JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS YEAR_MAX
    FROM ECOLI_DATA
    GROUP BY YEAR
    ) Y
ON YEAR(D.DIFFERENTIATION_DATE) = Y.YEAR
ORDER BY YEAR, YEAR_DEV;